easy_admin:
    design:
        menu:
            - {label: "Розділи"}
            - label: "Про нас"
              children:
                  - {entity: About, label: "Додати інформацію про нас", icon: "plus", params:{ action: "new"}}
            - label: "Зворотній зв'язок"
              children:
                  - {entity: Mailing, label: "Список листів", icon: "th-list"}
            - label: "Замовлення дзівнків"
              children:
                  - {entity: SendToCall, label: "Список замовлених дзвінків", icon: "th-list"}
            - label: "Етапи будівництва"
              children:
                  - {entity: BuildingStage, label: "Список фото етапів будівництва", icon: "th-list"}
                  - {entity: BuildingStage, label: "Додати фото етапу будівництва", icon: "camera", params:{ action: "new"}}
            - {label: "Налаштування"}
            - {entity: User, icon: "user"}
    site_name: "ЖК Італійський квартал"
    user:
        name_property_path: 'Username'
    entities:
        # List the entity class name you want to manage
        About:
            class: App\Entity\About
            label: "Про нас"
        BuildingStage:
            class: App\Entity\BuildingStage
            label: "Етапи будівництва"
            form:
                fields:
                    - {property: 'title', label: 'Назва'}
                    - {property: 'createdAt', label: 'Створений'}
                    - {property: 'updateAt', label: 'Оновлений'}
                    - {property: 'published', label: 'Опублікований'}
                    - {type: 'group', icon: 'img', label: "Малюнок" }
                    - {property: "thumbnailFile", label: "Виберіть файл", type: 'vich_image'}

            list:
                collapse_actions: true
                actions: ['show', 'edit', 'delete']
                batch_actions: ['delete']
                fields: [{property: 'title', label: 'Назва'}, {property: 'createdAt', label: 'Створений'}, {property: 'updateAt', label: 'Оновлений'}, {property: 'published', label: 'Опублікований'}, {property: 'nameImage', type: 'image', base_path: '%uploads_path%'} ]
                filters: ['published']
            show:
                fields:
                    - {property: 'title', label: 'Назва'}
                    - {property: 'createdAt', label: 'Створений'}
                    - {property: 'updateAt', label: 'Оновлений'}
                    - {property: 'published', label: 'Опублікований'}
                    - {property: 'nameImage', type: 'image', base_path: '%uploads_path%'}
        Mailing:
            class: App\Entity\Mailing
            label: "Зворотній зв'язок"
            list:
                collapse_actions: true
                actions: ['show', 'edit', 'delete']
                batch_actions: ['delete']
        SendToCall:
            class: App\Entity\SendToCall
            label: "Замовлення дзвіків"
            list:
                collapse_actions: true
                actions: ['show', 'edit', 'delete']
                batch_actions: ['delete']
        User:
            class: App\Entity\User
            label: "Користувачі"
            list:
                items_permission: 'ROLE_ADMIN'

