easy_admin:
    design:
        menu:
            - {label: "Entities"}
            - label: "About"
              children:
                  - {entity: About, label: "About add", icon: "plus", params:{ action: "new"}}
            - label: "Mailing"
              children:
                  - {entity: Mailing, label: "Mailing list", icon: "th-list"}
            - label: "Calling"
              children:
                  - {entity: SendToCall, label: "Calling list", icon: "th-list"}
            - label: "Building Stage"
              children:
                  - {entity: BuildingStage, label: "List Building stage photo", icon: "th-list"}
                  - {entity: BuildingStage, label: "Add Building stage photo", icon: "camera", params:{ action: "new"}}
            - {label: "Settings"}
            - {entity: User, icon: "user"}
    site_name: "ЖК Італійський квартал"
    user:
        name_property_path: 'Username'
    entities:
        # List the entity class name you want to manage
        About:
            class: App\Entity\About
            label: "About"
        BuildingStage:
            class: App\Entity\BuildingStage
            label: "Building stage"
            form:
                fields:
                    - title
                    - createdAt
                    - updateAt
                    - published
                    - {type: 'group', icon: 'img', label: "image" }
                    - {property: "thumbnailFile", label: "Choose file", type: 'vich_image'}

            list:
                collapse_actions: true
                actions: ['show', 'edit', 'delete']
                batch_actions: ['delete']
                fields: ['title', 'createdAt', 'updateAt', 'published', {property: 'nameImage', type: 'image', base_path: '%uploads_path%'} ]
                filters: ['published']
            show:
                fields:
                    - title
                    - createdAt
                    - updateAt
                    - published
                    - {property: 'nameImage', type: 'image', base_path: '%uploads_path%'}
        Mailing:
            class: App\Entity\Mailing
            label: "Mailing"
            list:
                collapse_actions: true
                actions: ['show', 'edit', 'delete']
                batch_actions: ['delete']
        SendToCall:
            class: App\Entity\SendToCall
            label: "Calling"
            list:
                collapse_actions: true
                actions: ['show', 'edit', 'delete']
                batch_actions: ['delete']
        User:
            class: App\Entity\User
            label: "User"
            list:
                items_permission: 'ROLE_ADMIN'

